core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("tienda/", include("tienda.urls", namespace="tienda")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

from .views import (
    BlogCreateView,
    BlogDetailView,
    TiendaView,
    BlogUpdateView,
    BlogDeleteView,
    UserCreateView,
    LoginUser,
    ExitUser,
    TusProductos,
    UserUpdateView,
    BlogDetailViewUser,
    VerCarro,
    BorrarProductoCarro,
    ProcesarCompra,
    HistorialTransacciones,
    UsuarioDetalleView,
)

app_name = "tienda"

urlpatterns = [
    # urls de post
    path("", TiendaView.as_view(), name="home"),
    path("create-post/", BlogCreateView.as_view(), name="create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("<int:pk>/user/", BlogDetailViewUser.as_view(), name="detailUser"),
    path("<int:pk>/update-post/", BlogUpdateView.as_view(), name="update"),
    path("<int:pk>/delete-post/", BlogDeleteView.as_view(), name="delete"),
    # -----------------------------------------------------------------------
    # url de usuario
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", ExitUser.as_view(), name="logout"),
    path("usuario/<int:pk>/", UsuarioDetalleView.as_view(), name="usuario_detalle"),
    path("<int:pk>/user-update/", UserUpdateView.as_view(), name="userUpdate"),
    path("<int:user_id>/tus-post/", TusProductos.as_view(), name="tusPost"),
    # ------------------------------------------------------------------------
    # urls de compras y transacciones
    path(
        "agregar_compra/<int:post_id>/", views.agregar_a_compra, name="agregar_compra"
    ),
    path("carro-compra/<int:user_id>", VerCarro.as_view(), name="carro"),
    path("carro/borrar/<int:pk>/", BorrarProductoCarro.as_view(), name="delete_carro"),
    path("carro/procesar/", ProcesarCompra.as_view(), name="procesar_compra"),
    path(
        "historial-transacciones/",
        HistorialTransacciones.as_view(),
        name="historial_transacciones",
    ),
]

templates/compras/carro_compra.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Tu Carrito de Compras</h2>

    {% if not compras %}
        <p class="text-center text-gray-600 mt-8">No tienes nada en el carro</p>
    {% else %}

    {% if total_compra == 1 %}       
        <h2 class="text-3xl font-bold mb-6">Tienes {{total_compra}} producto en tu carrito</h2>
    {% else %}
        <h2 class="text-3xl font-bold mb-6">Tienes {{total_compra}} productos en tu carrito</h2>
    {% endif %}
    <br>
    <div class="overflow-x-auto shadow-md">
        <table class="min-w-full bg-white border border-gray-300">
            <thead class="bg-gray-700 text-white">
                <tr>
                    <th class="py-2 px-4 text-left" style="width: 300px;">Producto</th>
                    <th class="py-2 px-4 text-left" style="width: 100px;">Precio</th>
                    <th class="py-2 px-4 text-center" style="width: 100px;">Acciones</th>
                </tr>
            </thead>
            <tbody>
                {% for compra in compras %}
                <tr class="border-b border-gray-200">
                    <td class="py-2 px-4" style="width: 300px;">{{ compra.nombreCompra }}</td>
                    <td class="py-2 px-4" style="width: 100px;">${{ compra.precioCompra }}</td>
                    <td class="py-2 px-4" style="width: 100px;">
                        <div class="flex justify-center">
                            <a href="{% url 'tienda:delete_carro' compra.id %}" class="text-red-600 hover:text-red-800 font-bold ">Eliminar</a>
                        </div>
                        
                    </td>
                </tr>
                {% endfor %}
                <tr class="border-t-2 border-gray-300 bg-gray-100">
                    <td class="py-2 px-4 font-bold" >Total</td>
                    <td class="py-2 px-4 font-bold">${{ total_precio }}</td>
                    <td></td>
                </tr>
            </tbody>
        </table>
    </div>

    <form action="{% url 'tienda:procesar_compra' %}" method="POST" class="flex justify-end mt-4">
        {% csrf_token %}
        <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            Procesar Compra
        </button>
    </form>

{% endif %}
<br>
<a href="{% url "tienda:home" %}" class="text-blue-500 hover:text-blue-700">
    &larr; Atrás
</a>
</div>
{% endblock content %}

templates/compras/carro_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto p-4 mt-32">
    <div class="bg-white rounded-lg shadow-lg p-6 text-center">
        <!-- Título y mensaje de confirmación -->
        <h2 class="text-2xl font-bold mb-4 text-red-600">Confirmar Eliminación</h2>
        <p class="text-lg text-gray-700 mb-6">
            ¿Estás seguro de que quieres eliminar "{{ compra.nombreCompra }}" de tu carro?
        </p>

        <!-- Formulario de confirmación -->
        <form action="" method="POST" class="space-y-4">
            {% csrf_token %}
            {{ form.as_p }}
            
            <!-- Botones de acción -->
            <div class="flex justify-center space-x-4">
                <a href="javascript:history.back()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Volver
                </a>
                <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                    Eliminar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/compras/historial_compra.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Historial de Transacciones</h2>

    {% if not transacciones %}
        <p class="text-center text-gray-600 mt-8">No tienes transacciones realizadas</p>
    {% else %}
        <div class="overflow-x-auto">
            <table class="min-w-full bg-white border border-gray-300">
                <thead class="bg-gray-700 text-white ">
                    <tr>
                        <th class="py-2 px-4 text-left ">Fecha transaccion</th>
                        <th class="py-2 px-4 text-left">cantidad de compra</th>
                        <th class="py-2 px-4 text-left">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {% for transaccion in transacciones %}
                    <tr class="border-b border-gray-200">
                        <td class="py-2 px-4">{{ transaccion.fecha }}</td>
                        <td class="py-2 px-4">{{ transaccion.cantidadCompra }}</td>
                        <td class="py-2 px-4">${{ transaccion.totalCompra }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
        <br>
    <a href="{% url 'tienda:usuario_detalle' user.pk %}" class="text-blue-500 hover:text-blue-700">
        &larr; Atrás
    </a>
</div>
{% endblock content %}