core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("tienda/", include("tienda.urls", namespace="tienda")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

from .views import (
    BlogCreateView,
    BlogDetailView,
    TiendaView,
    BlogUpdateView,
    BlogDeleteView,
    UserCreateView,
    LoginUser,
    ExitUser,
    TusProductos,
    UserUpdateView,
    BlogDetailViewUser,
    VerCarro,
    BorrarProductoCarro,
    ProcesarCompra,
    HistorialTransacciones,
    UsuarioDetalleView,
)

app_name = "tienda"

urlpatterns = [
    # urls de post
    path("", TiendaView.as_view(), name="home"),
    path("create-post/", BlogCreateView.as_view(), name="create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("<int:pk>/user/", BlogDetailViewUser.as_view(), name="detailUser"),
    path("<int:pk>/update-post/", BlogUpdateView.as_view(), name="update"),
    path("<int:pk>/delete-post/", BlogDeleteView.as_view(), name="delete"),
    # -----------------------------------------------------------------------
    # url de usuario
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", ExitUser.as_view(), name="logout"),
    path("usuario/<int:pk>/", UsuarioDetalleView.as_view(), name="usuario_detalle"),
    path("<int:pk>/user-update/", UserUpdateView.as_view(), name="userUpdate"),
    path("<int:user_id>/tus-post/", TusProductos.as_view(), name="tusPost"),
    # ------------------------------------------------------------------------
    # urls de compras y transacciones
    path(
        "agregar_compra/<int:post_id>/", views.agregar_a_compra, name="agregar_compra"
    ),
    path("carro-compra/<int:user_id>", VerCarro.as_view(), name="carro"),
    path("carro/borrar/<int:pk>/", BorrarProductoCarro.as_view(), name="delete_carro"),
    path("carro/procesar/", ProcesarCompra.as_view(), name="procesar_compra"),
    path(
        "historial-transacciones/",
        HistorialTransacciones.as_view(),
        name="historial_transacciones",
    ),
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# tabla Post
class Post(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200, blank=True, null=True)
    marca = models.CharField(max_length=100)
    img = models.ImageField(upload_to="posts/", blank=True, null=True)
    price = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=0)
    content = models.TextField()
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


# tabla carroCompra
class Compra(models.Model):

    nombreCompra = models.CharField(max_length=100, null=False)
    precioCompra = models.IntegerField(default=0, null=False)

    # clave_foranea
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    postID = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreCompra


# tabla transaccion
class TransaccionCompra(models.Model):

    totalCompra = models.PositiveIntegerField(default=0)
    cantidadCompra = models.PositiveIntegerField(default=0)
    fecha = models.DateTimeField(auto_now_add=True)
    # clave_foranea
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Transacción {self.id} ({self.fecha})"

templates/productos/blog_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Crear Nuevo Artículo</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
        
        <!-- Campo de Título -->
        <div class="mb-4">
            <label for="id_title" class="block text-lg font-semibold text-gray-700 mb-2">Título:</label>
            <input type="text" name="title" value="{{ form.title.value|default_if_none:'' }}" id="id_title" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Bajada -->
        <div class="mb-4">
            <label for="id_sub_title" class="block text-lg font-semibold text-gray-700 mb-2">Bajada:</label>
            <textarea name="sub_title" id="id_sub_title" rows="4" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.sub_title.value|default_if_none:'' }}</textarea>
        </div>
        
        <!-- Campo de Marca -->
        <div class="mb-4">
            <label for="id_marca" class="block text-lg font-semibold text-gray-700 mb-2">Marca:</label>
            <input type="text" name="marca" value="{{ form.marca.value|default_if_none:'' }}" id="id_marca" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Imagen -->
        <div class="mb-4">
            <label for="id_img" class="block text-lg font-semibold text-gray-700 mb-2">Imagen:</label>
            <input type="file" name="img" id="id_img" class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none">
        </div>
        
        <!-- Campo de Precio -->
        <div class="mb-4">
            <label for="id_price" class="block text-lg font-semibold text-gray-700 mb-2">Precio:</label>
            <input type="number" name="price" value="{{ form.price.value|default_if_none:'' }}" id="id_price" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Cantidad -->
        <div class="mb-4">
            <label for="id_amount" class="block text-lg font-semibold text-gray-700 mb-2">Cantidad:</label>
            <input type="number" name="amount" value="{{ form.amount.value|default_if_none:'' }}" id="id_amount" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Detalles -->
        <div class="mb-4">
            <label for="id_content" class="block text-lg font-semibold text-gray-700 mb-2">Detalles:</label>
            <textarea name="content" id="id_content" rows="6" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        
        <!-- Botones de Acción -->
        <div class="flex justify-between items-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Subir</button>
            <a href="javascript:history.back()" class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">Atrás</a>
        </div>
    </form>
</div>  
{% endblock content %}

templates/productos/blog_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto p-4">
    <div class="bg-white rounded-lg shadow-lg p-6 text-center">
        <!-- Título y mensaje de confirmación -->
        <h2 class="text-2xl font-bold mb-4 text-red-600">Confirmar Eliminación</h2>
        <p class="text-lg text-gray-700 mb-6">
            ¿Estás seguro de que quieres eliminar "{{ post.title }}"?
        </p>

        <!-- Formulario de confirmación -->
        <form action="" method="POST" class="space-y-4">
            {% csrf_token %}
            {{ form.as_p }}
            
            <!-- Botones de acción -->
            <div class="flex justify-center space-x-4">
                <a href="javascript:history.back()" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Volver
                </a>
                <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                    Eliminar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/productos/blog_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container rounded-lg shadow-lg bg-white mx-auto p-4 mt-32">
    <div class="  p-6 flex">
        <!-- Imagen del Post -->
        <div class="w-1/3">
            {% if post.img %}
                <img class="w-full h-auto object-cover rounded-lg" src="{{ post.img.url }}" alt="{{ post.title }}">
            {% else %}
                <img class="w-full h-auto object-cover rounded-lg" src="{% static 'media\images\no-img.png' %}" alt="Imagen predeterminada">
            {% endif %}
        </div>

        <!-- Detalles del Post -->
        <div class="w-2/3 pl-6">
            <!-- Título del Post -->
            <h1 class="text-3xl font-bold mb-2">{{ post.title }}</h1>
            
            <!-- Subtítulo del Post -->
            <p class="text-xl text-gray-700 mb-4">{{ post.sub_title }}</p>
            
            <!-- Precio -->
            <p class="text-2xl font-semibold text-green-500 mb-2">${{ post.price }}</p>
            
            <!-- Cantidad -->
             {% if  post.amount  == 1 %}
            <p class="text-lg text-gray-600 mb-4">{{ post.amount }} unidad disponible</p>
            {% else %}
            <p class="text-lg text-gray-600 mb-4">{{ post.amount }} unidades disponibles</p>
            {% endif %}
            <!-- Contenido del Post -->
            <p class="text-gray-700 mb-6">{{ post.content }}</p>

            <!-- Botones de Acción -->
             <br>
             <div class="space-x-4 mb-4 ">
                <form action="{% url 'tienda:agregar_compra' post.id %}" method="POST">
                    {% if post.amount >= 1 %}
                        {% csrf_token %}
                        {% if user.is_authenticated %}
                            <button type="submit" class="flex items-center bg-yellow-400 hover:bg-yellow-600 text-black font-bold  py-2 px-4 rounded mb-4">
                                <img class="w-5 h-5 rounded-full" src="/media/images/carro.png" alt="img carro">
                                <span class="ml-2">Agregar al Carrito</span>
                            </button>
                        {% else %}
                            <h5 class="text-red-600">Debes iniciar sesión para comprar, <a class="text-blue-600 hover:text-blue-800 font-bold" href="{% url 'tienda:login' %}">Inicia sesión aquí</a></h5>
                        {% endif %}
                    {% else %}
                        <button type="button" class="flex items-center bg-gray-500 hover:bg-gray-400 text-black font-bold  py-2 px-4 rounded mb-4">
                            <img class="w-5 h-5 rounded-full" src="/media/images/carro.png" alt="img carro">
                            <span class="ml-2">Sin existencias</span>
                        </button>                             
                    {% endif %}    
                </form>
            
                </div> 
            

            
        </div>
    </div>
    

    <a href="javascript:history.back()" class="text-blue-500 hover:text-blue-700">
        &larr; Atrás
    </a>
</div>
{% endblock content %}

templates/productos/blog_detail_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container rounded-lg shadow-lg bg-white mx-auto p-4 mt-32">

    
    <div class="  p-6 flex">
        <!-- Imagen del Post -->
        <div class="w-1/3">
            {% if post.img %}
                <img class="w-full h-auto object-cover rounded-lg" src="{{ post.img.url }}" alt="{{ post.title }}">
            {% else %}
                <img class="w-full h-auto object-cover rounded-lg" src="{% static 'media\images\no-img.png' %}" alt="Imagen predeterminada">
            {% endif %}
        </div>

        <!-- Detalles del Post -->
        <div class="w-2/3 pl-6">
            <!-- Título del Post -->
            <h1 class="text-3xl font-bold mb-2">{{ post.title }}</h1>
            
            <!-- Subtítulo del Post -->
            <p class="text-xl text-gray-700 mb-4">{{ post.sub_title }}</p>
            
            <!-- Precio -->
            <p class="text-2xl font-semibold text-green-500 mb-2">${{ post.price }}</p>
            
            <!-- Cantidad -->
            <p class="text-lg text-gray-600 mb-4">{{ post.amount }} unidades disponibles</p>
            
            <!-- Contenido del Post -->
            <p class="text-gray-700 mb-6">{{ post.content }}</p>

            

            
        </div>

        

    </div>

    <!-- Botones de Acción -->
             
    <div class="flex justify-end space-x-4 mb-4">
        <a href="{% url 'tienda:update' post.id %}">
            <button type="button" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Editar
            </button>
        </a>
        <a href="{% url 'tienda:delete' post.id %}">
            <button type="button" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                Eliminar
            </button>
        </a>
    </div>
    <a href="{% url "tienda:home" %}" class="text-blue-500 hover:text-blue-700">
        &larr; Atrás
    </a>
</div>
{% endblock content %}

templates/productos/blog_list_tienda.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Bucle para mostrar los posts -->
 <div class="mt-32 mb-32 ">

  {% for post in posts %}
  <div class="container mx-auto mt-4">
    
    <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl hover:shadow-2xl hover:-translate-y-px">
      <a href="{% url 'tienda:detail' post.id %}">
        <div class="md:flex">
          
          <!-- Muestra la imagen del post -->
          <div class="md:shrink-0">
            {% if post.img %}
            <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.img.url }}" alt="Imagen de {{ post.title }}">
            {% else %}
            <img class="h-48 w-full object-cover md:h-full md:w-48" src="{% static 'media\images\no-img.png' %}" alt="Imagen por defecto">
            {% endif %}
          </div>

          <!-- Información del post -->
          <div class="p-8">
            <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">{{ post.title }}</div>
            <p class="block mt-1 text-xl leading-tight font-medium text-black">{{ post.sub_title }}</p>
            <p class="mt-2 text-lg text-green-500 font-bold">${{ post.price }}</p>
          </div>

        </div>
      </a>
    </div>
  </div>  
  {% endfor %}
</div>

{% if not posts %}
    <p class="text-center text-gray-600 mt-8">No hay publicaciones.</p>
    {% endif %}

{% endblock content %}

templates/productos/blog_list_user.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Contenedor principal -->
<div class="container mx-auto mt-32 mb-32 p-6 bg-gray-100 shadow-md rounded-lg ">

    <h2 class="text-3xl font-bold mb-6">Tus Posts</h2>

    <!-- Botón para crear un nuevo artículo -->
    <div class="text-right mb-6">
        <a href="{% url 'tienda:create' %}">
            <button type="button" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                Crear Nuevo Artículo
            </button>
        </a>
    </div>

    <!-- mostrar los posts -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 ">
        {% for post in posts %}

        <div class="bg-white rounded-xl shadow-md overflow-hidden hover:shadow-2xl hover:-translate-y-px">
            <a href="{% url 'tienda:detailUser' post.id %}">
                <div class="md:flex">
                    
                    <!-- imagen del post -->
                    <div class="md:shrink-0">
                        {% if post.img %}
                        <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.img.url }}" alt="Imagen de {{ post.title }}">
                        {% else %}
                        <img class="h-48 w-full object-cover md:h-full md:w-48" src="{% static 'media\images\no-img.png' %}" alt="Imagen por defecto">
                        {% endif %}
                    </div>

                    <!-- Info del post -->
                    <div class="p-6">
                        <h3 class="text-lg leading-tight font-semibold text-indigo-600">{{ post.title }}</h3>
                        <p class="block mt-1 text-base leading-tight font-medium text-black">{{ post.sub_title }}</p>
                        <p class="mt-2 text-gray-600">{{ post.content|truncatewords:20 }}</p> <!-- Truncate words to keep it concise -->
                    </div>

                </div>
            </a>
        </div>
        {% endfor %}
    </div>

    <!-- Mensaje en caso de que no haya posts -->
    {% if not posts %}
    <p class="text-center text-gray-600 mt-8">No tienes publicaciones.</p>
    {% endif %}
    
</div>

{% endblock content %}

templates/productos/blog_tienda_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Bucle para mostrar los posts -->
{% for post in posts %}
<div class="container mx-auto mt-4">
  
  <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
    <a href="{% url 'tienda:detail' post.id %}">
      <div class="md:flex">
        
        <!-- Muestra la imagen del post -->
        <div class="md:shrink-0">
          {% if post.img %}
          <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.img.url }}" alt="Imagen de {{ post.title }}">
          {% else %}
          <img class="h-48 w-full object-cover md:h-full md:w-48" src="{% static 'default_image.jpg' %}" alt="Imagen por defecto">
          {% endif %}
        </div>

        <!-- Información del post -->
        <div class="p-8">
          <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">{{ post.title }}</div>
          <p class="block mt-1 text-lg leading-tight font-medium text-black hover:underline">{{ post.sub_title }}</p>
          <p class="mt-2 text-slate-500">{{ post.content }}</p>
        </div>

      </div>
    </a>
  </div>

</div>  
{% endfor %}

{% if not posts %}
    <p class="text-center text-gray-600 mt-8">No hay publicaciones.</p>
    {% endif %}

{% endblock content %}

templates/productos/blog_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Modificar Artículo</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
        
        <!-- Campo de Título -->
        <div class="mb-4">
            <label for="id_title" class="block text-lg font-semibold text-gray-700 mb-2">Título:</label>
            <input type="text" name="title" value="{{ form.title.value|default_if_none:'' }}" id="id_title" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Bajada -->
        <div class="mb-4">
            <label for="id_sub_title" class="block text-lg font-semibold text-gray-700 mb-2">Bajada:</label>
            <textarea name="sub_title" id="id_sub_title" rows="4" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.sub_title.value|default_if_none:'' }}</textarea>
        </div>
        
        <!-- Campo de Marca -->
        <div class="mb-4">
            <label for="id_marca" class="block text-lg font-semibold text-gray-700 mb-2">Marca:</label>
            <input type="text" name="marca" value="{{ form.marca.value|default_if_none:'' }}" id="id_marca" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Imagen -->
        <div class="mb-4">
            <label class="block text-lg font-semibold text-gray-700 mb-2">Imagen Actual:</label>
            <img class="w-48 h-auto object-cover rounded-lg mb-2" src="{{ post.img.url }}" alt="{{ post.title }}">
            <label for="id_img" class="block text-lg font-semibold text-gray-700 mb-2">Nueva Imagen (opcional):</label>
            <input type="file" name="img" id="id_img" class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none">
        </div>
        
        <!-- Campo de Precio -->
        <div class="mb-4">
            <label for="id_price" class="block text-lg font-semibold text-gray-700 mb-2">Precio:</label>
            <input type="number" name="price" value="{{ form.price.value|default_if_none:'' }}" id="id_price" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Cantidad -->
        <div class="mb-4">
            <label for="id_amount" class="block text-lg font-semibold text-gray-700 mb-2">Cantidad:</label>
            <input type="number" name="amount" value="{{ form.amount.value|default_if_none:'' }}" id="id_amount" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Detalles -->
        <div class="mb-4">
            <label for="id_content" class="block text-lg font-semibold text-gray-700 mb-2">Detalles:</label>
            <textarea name="content" id="id_content" rows="6" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        
        <!-- Botones de Acción -->
        <div class="flex justify-between items-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Actualizar</button>
            <a href="javascript:history.back()" class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">Atrás</a>
        </div>
    </form>
</div>  
{% endblock content %}

templates/productos/carro_compra.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-8 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Tu Carrito de Compras</h2>

    {% if not compras %}
        <p class="text-center text-gray-600 mt-8">No tienes nada en el carro</p>
    {% else %}

    {% if total_compra == 1 %}       
        <h2 class="text-3xl font-bold mb-6">Tienes {{total_compra}} producto en tu carrito</h2>
    {% else %}
        <h2 class="text-3xl font-bold mb-6">Tienes {{total_compra}} productos en tu carrito</h2>
    {% endif %}
    <br>
        <div class="bg-zinc-600 p-3 border-emerald-500">
            <table class="min-w-full ">
                <thead>
                    <tr>
                    
                        <th class=" py-2 bg-zinc-600 text-white">Producto</th>
                        <th class=" py-2 bg-zinc-600 text-white">Precio</th>
                    </tr>
                </thead>
                <tbody>
                    {% for compra in compras %}
                    <tr>
                        
                        <td class="border px-0  py-2 bg-zinc-300">- {{ compra.nombreCompra }}</td>
                        <td class="border px-0 py-2 bg-zinc-300">${{ compra.precioCompra }}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        
                        <td class="border px-0 py-2 bg-zinc-600 text-white font-bold">Total</td>
                        <td class="border px-0 py-2 font-bold bg-zinc-600 text-white">${{ total_precio }}</td>
                    </tr>
                </tbody>
            </table>
        </div>
        <br>
        <div class="flex justify-end">
            <a href="#" class="mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Procesar Compra</a>
        </div>
    {% endif %}
</div>
{% endblock content %}