core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("tienda/", include("tienda.urls", namespace="tienda")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

from .views import (
    BlogCreateView,
    BlogDetailView,
    TiendaView,
    BlogUpdateView,
    BlogDeleteView,
    UserCreateView,
    LoginUser,
    ExitUser,
    TusProductos,
    UserUpdateView,
    BlogDetailViewUser,
    VerCarro,
    BorrarProductoCarro,
    ProcesarCompra,
    HistorialTransacciones,
    UsuarioDetalleView,
)

app_name = "tienda"

urlpatterns = [
    # urls de post
    path("", TiendaView.as_view(), name="home"),
    path("create-post/", BlogCreateView.as_view(), name="create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("<int:pk>/user/", BlogDetailViewUser.as_view(), name="detailUser"),
    path("<int:pk>/update-post/", BlogUpdateView.as_view(), name="update"),
    path("<int:pk>/delete-post/", BlogDeleteView.as_view(), name="delete"),
    # -----------------------------------------------------------------------
    # url de usuario
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", ExitUser.as_view(), name="logout"),
    path("usuario/<int:pk>/", UsuarioDetalleView.as_view(), name="usuario_detalle"),
    path("<int:pk>/user-update/", UserUpdateView.as_view(), name="userUpdate"),
    path("<int:user_id>/tus-post/", TusProductos.as_view(), name="tusPost"),
    # ------------------------------------------------------------------------
    # urls de compras y transacciones
    path(
        "agregar_compra/<int:post_id>/", views.agregar_a_compra, name="agregar_compra"
    ),
    path("carro-compra/<int:user_id>", VerCarro.as_view(), name="carro"),
    path("carro/borrar/<int:pk>/", BorrarProductoCarro.as_view(), name="delete_carro"),
    path("carro/procesar/", ProcesarCompra.as_view(), name="procesar_compra"),
    path(
        "historial-transacciones/",
        HistorialTransacciones.as_view(),
        name="historial_transacciones",
    ),
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# tabla Post
class Post(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200, blank=True, null=True)
    marca = models.CharField(max_length=100)
    img = models.ImageField(upload_to="posts/", blank=True, null=True)
    price = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=0)
    content = models.TextField()
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


# tabla carroCompra
class Compra(models.Model):

    nombreCompra = models.CharField(max_length=100, null=False)
    precioCompra = models.IntegerField(default=0, null=False)

    # clave_foranea
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    postID = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreCompra


# tabla transaccion
class TransaccionCompra(models.Model):

    totalCompra = models.PositiveIntegerField(default=0)
    cantidadCompra = models.PositiveIntegerField(default=0)
    fecha = models.DateTimeField(auto_now_add=True)
    # clave_foranea
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Transacción {self.id} ({self.fecha})"

templates/usuarios/user_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Registro</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
        
        <!-- Campo de nombre -->
        <div class="mb-4">
            <label for="id_username" class="block text-lg font-semibold text-gray-700 mb-2">Nombre de Usuario:</label>
            {{ form.username }}
            {% if form.username.errors %}
                <p class="text-red-500 text-xs italic">{{ form.username.errors }}</p>
            {% endif %}
        </div>
        
        <!-- Campo de email -->
        <div class="mb-4">
            <label for="id_email" class="block text-lg font-semibold text-gray-700 mb-2">Email:</label>
            {{ form.email }}
            {% if form.email.errors %}
                <p class="text-red-500 text-xs italic">{{ form.email.errors }}</p>
            {% endif %}
        </div>
        
        <!-- Campo de password1 -->
        <div class="mb-4">
            <label for="id_password1" class="block text-lg font-semibold text-gray-700 mb-2">Contraseña:</label>
            {{ form.password1 }}
            {% if form.password1.errors %}
                <p class="text-red-500 text-xs italic">{{ form.password1.errors }}</p>
            {% endif %}
        </div>

         <!-- Campo de password2 -->
        <div class="mb-4">
            <label for="id_password2" class="block text-lg font-semibold text-gray-700 mb-2">Confirmar Contraseña:</label>
            {{ form.password2 }}
            {% if form.password2.errors %}
                <p class="text-red-500 text-xs italic">{{ form.password2.errors }}</p>
            {% endif %}
        </div>

        <!-- Botones de Acción -->
        <div class="flex justify-between items-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Crear Usuario</button>
            <a href="javascript:history.back()" class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">Atrás</a>
        </div>
    </form>
</div>  
{% endblock content %}

templates/usuarios/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Detalles del Usuario</h2>

    <div class="mb-6">
        <p class="text-xl"><strong>Nombre de usuario:</strong> {{ usuario.username }}</p>
        <p class="text-xl"><strong>Email:</strong> {{ usuario.email }}</p>
        
    </div>

    <div class="mb-6">
        <a href="{% url 'tienda:userUpdate' usuario.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Editar Perfil</a>
    </div>

    <h3 class="text-2xl font-bold mb-4 mt-32">Transacciones</h3>

    {% if transacciones %}
        <table class="min-w-full bg-white border border-gray-300 shadow-md">
            <thead class="bg-gray-700 text-white">
                <tr>
                    <th class="py-2 px-4 text-center">Fecha Transaccion</th>
                    <th class="py-2 px-4 text-center">Total Compra</th>
                    <th class="py-2 px-4 text-center">Cantidad</th>
                   
                </tr>
            </thead>
            <tbody>
                {% for transaccion in transacciones %}
                <tr class="border-b border-gray-200">
                    <td class="py-2 px-4 text-center">{{ transaccion.fecha }}</td>
                    <td class="py-2 px-4 text-center">${{ transaccion.totalCompra }}</td>
                    <td class="py-2 px-4 text-center">{{ transaccion.cantidadCompra }}</td>
                    
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="text-gray-600 mt-8">No tienes transacciones.</p>
    {% endif %}
        <br>
    <a href="{% url "tienda:home" %}" class="text-blue-500 hover:text-blue-700 ">
        &larr; Atrás
    </a>
</div>
{% endblock content %}

templates/usuarios/user_login.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<div class="min-h-screen flex items-center justify-center bg-gray-100 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                Iniciar Sesión
            </h2>
            <p class="mt-2 text-center text-sm text-gray-600">
                O 
                <a href="{% url 'tienda:register' %}" class="font-medium text-indigo-600 hover:text-indigo-500">
                    regístrate para una nueva cuenta
                </a>
            </p>
        </div>

        <form class="mt-8 space-y-6" action="" method="post">
            {% csrf_token %}
            
            <!-- Mostrar errores de autenticación si existen -->
            {% if form.errors %}
                <div class="rounded-md bg-red-50 p-4">
                    <div class="flex">
                        <div class="ml-3">
                            <h3 class="text-sm font-medium text-red-800">Error al ingresar los datos</h3>
                            
                        </div>
                    </div>
                </div>
            {% endif %}

            <div class="rounded-md shadow-sm -space-y-px">
                <div>
                    <label for="username" class="sr-only">Nombre de Usuario</label>
                    <input id="username" name="username" type="text" autocomplete="username" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Nombre de Usuario">
                </div>
                <div>
                    <label for="password" class="sr-only">Contraseña</label>
                    <input id="password" name="password" type="password" autocomplete="current-password" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Contraseña">
                </div>
            </div>

            <div>
                <button type="submit"
                    class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    Iniciar Sesión
                </button>
            </div>

            <a href="javascript:history.back()" style="text-decoration: none; color: inherit;">
                <div class="flex justify-between">
                    
                    <button type="button" 
                        class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-indigo-600 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                        Atrás
                    </button>
                </div>
            </a>
        </form>
    </div>
</div>

{% endblock content %}

templates/usuarios/user_update.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-32 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Ajustes de usuario</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
        
        <!-- Campo de Título -->
        <div class="mb-4">
            <label for="id_title" class="block text-lg font-semibold text-gray-700 mb-2">Nombre:</label>
            <input type="text" name="username" value="{{ form.username.value|default_if_none:'' }}" id="id_title" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de email -->
        <div class="mb-4">
            <label for="id_email" class="block text-lg font-semibold text-gray-700 mb-2">Email:</label>
            <input type="email" name="email" value="{{ form.email.value|default_if_none:'' }}" id="id_email" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        
        <!-- Botones de Acción -->
        <div class="flex justify-between items-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Actualizar</button>
            <a href="javascript:history.back()" class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">Atrás</a>
        </div>
    </form>
</div>  
{% endblock content %}