core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from .views import HomeView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("tienda/", include("tienda.urls", namespace="tienda")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tienda/urls.py
from django.urls import path
from . import views

from .views import (
    BlogCreateView,
    BlogDetailView,
    TiendaView,
    BlogUpdateView,
    BlogDeleteView,
    UserCreateView,
    LoginUser,
    ExitUser,
    TusProductos,
    UserUpdateView,
    BlogDetailViewUser,
    VerCarro,
    BorrarProductoCarro,
    ProcesarCompra,
    HistorialTransacciones,
    UsuarioDetalleView,
)

app_name = "tienda"

urlpatterns = [
    # urls de post
    path("", TiendaView.as_view(), name="home"),
    path("create-post/", BlogCreateView.as_view(), name="create"),
    path("<int:pk>/", BlogDetailView.as_view(), name="detail"),
    path("<int:pk>/user/", BlogDetailViewUser.as_view(), name="detailUser"),
    path("<int:pk>/update-post/", BlogUpdateView.as_view(), name="update"),
    path("<int:pk>/delete-post/", BlogDeleteView.as_view(), name="delete"),
    # -----------------------------------------------------------------------
    # url de usuario
    path("register/", UserCreateView.as_view(), name="register"),
    path("login/", LoginUser.as_view(), name="login"),
    path("logout/", ExitUser.as_view(), name="logout"),
    path("usuario/<int:pk>/", UsuarioDetalleView.as_view(), name="usuario_detalle"),
    path("<int:pk>/user-update/", UserUpdateView.as_view(), name="userUpdate"),
    path("<int:user_id>/tus-post/", TusProductos.as_view(), name="tusPost"),
    # ------------------------------------------------------------------------
    # urls de compras y transacciones
    path(
        "agregar_compra/<int:post_id>/", views.agregar_a_compra, name="agregar_compra"
    ),
    path("carro-compra/<int:user_id>", VerCarro.as_view(), name="carro"),
    path("carro/borrar/<int:pk>/", BorrarProductoCarro.as_view(), name="delete_carro"),
    path("carro/procesar/", ProcesarCompra.as_view(), name="procesar_compra"),
    path(
        "historial-transacciones/",
        HistorialTransacciones.as_view(),
        name="historial_transacciones",
    ),
]

tienda/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


# tabla Post
class Post(models.Model):
    title = models.CharField(max_length=100)
    sub_title = models.CharField(max_length=200, blank=True, null=True)
    marca = models.CharField(max_length=100)
    img = models.ImageField(upload_to="posts/", blank=True, null=True)
    price = models.PositiveIntegerField(default=0)
    amount = models.PositiveIntegerField(default=0)
    content = models.TextField()
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


# tabla carroCompra
class Compra(models.Model):

    nombreCompra = models.CharField(max_length=100, null=False)
    precioCompra = models.IntegerField(default=0, null=False)

    # clave_foranea
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    postID = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.nombreCompra


# tabla transaccion
class TransaccionCompra(models.Model):

    totalCompra = models.PositiveIntegerField(default=0)
    cantidadCompra = models.PositiveIntegerField(default=0)
    fecha = models.DateTimeField(auto_now_add=True)
    # clave_foranea
    usuarioID = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"Transacción {self.id} ({self.fecha})"

templates/Blog_create.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto mt-8 p-6 bg-white shadow-md rounded-lg">
    <h2 class="text-3xl font-bold mb-6">Crear Nuevo Artículo</h2>

    <form action="" method="POST" enctype="multipart/form-data" class="space-y-6">
        {% csrf_token %}
        
        <!-- Campo de Título -->
        <div class="mb-4">
            <label for="id_title" class="block text-lg font-semibold text-gray-700 mb-2">Título:</label>
            <input type="text" name="title" value="{{ form.title.value|default_if_none:'' }}" id="id_title" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Bajada -->
        <div class="mb-4">
            <label for="id_sub_title" class="block text-lg font-semibold text-gray-700 mb-2">Bajada:</label>
            <textarea name="sub_title" id="id_sub_title" rows="4" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.sub_title.value|default_if_none:'' }}</textarea>
        </div>
        
        <!-- Campo de Marca -->
        <div class="mb-4">
            <label for="id_marca" class="block text-lg font-semibold text-gray-700 mb-2">Marca:</label>
            <input type="text" name="marca" value="{{ form.marca.value|default_if_none:'' }}" id="id_marca" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Imagen -->
        <div class="mb-4">
            <label for="id_img" class="block text-lg font-semibold text-gray-700 mb-2">Imagen:</label>
            <input type="file" name="img" id="id_img" class="block w-full text-sm text-gray-900 border border-gray-300 rounded-lg cursor-pointer bg-gray-50 focus:outline-none">
        </div>
        
        <!-- Campo de Precio -->
        <div class="mb-4">
            <label for="id_price" class="block text-lg font-semibold text-gray-700 mb-2">Precio:</label>
            <input type="number" name="price" value="{{ form.price.value|default_if_none:'' }}" id="id_price" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Cantidad -->
        <div class="mb-4">
            <label for="id_amount" class="block text-lg font-semibold text-gray-700 mb-2">Cantidad:</label>
            <input type="number" name="amount" value="{{ form.amount.value|default_if_none:'' }}" id="id_amount" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">
        </div>
        
        <!-- Campo de Detalles -->
        <div class="mb-4">
            <label for="id_content" class="block text-lg font-semibold text-gray-700 mb-2">Detalles:</label>
            <textarea name="content" id="id_content" rows="6" class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        
        <!-- Botones de Acción -->
        <div class="flex justify-between items-center">
            <button type="submit" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Subir</button>
            <a href="{% url 'tienda:home' %}" class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded">Atrás</a>
        </div>
    </form>
</div>  
{% endblock content %}

templates/Blog_delete.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mx-auto p-4">
    <div class="bg-white rounded-lg shadow-lg p-6 text-center">
        <!-- Título y mensaje de confirmación -->
        <h2 class="text-2xl font-bold mb-4 text-red-600">Confirmar Eliminación</h2>
        <p class="text-lg text-gray-700 mb-6">
            ¿Estás seguro de que quieres eliminar "{{ post.title }}"?
        </p>

        <!-- Formulario de confirmación -->
        <form action="" method="POST" class="space-y-4">
            {% csrf_token %}
            {{ form.as_p }}
            
            <!-- Botones de acción -->
            <div class="flex justify-center space-x-4">
                <a href="{% url 'tienda:detail' post.id %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
                    Volver
                </a>
                <button type="submit" class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
                    Eliminar
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

templates/base.html
{% load static tailwind_tags %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La tiendita</title>
    {% tailwind_css %}
</head>
<body class="bg-gray-700">



<nav class="bg-white border-gray-200 dark:bg-gray-900 fixed top-0 left-0 w-full z-10">
    <div class="max-w-screen-xl flex flex-wrap items-center justify-between mx-auto p-4">
    <a href="{% url 'tienda:login' %}" class="flex items-center space-x-3 rtl:space-x-reverse">
        <img src="https://flowbite.com/docs/images/logo.svg" class="h-8" alt="Flowbite Logo" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">La Tiendita</span>
    </a>
    <div class="flex items-center md:order-2 space-x-3 md:space-x-0 rtl:space-x-reverse">

    {% comment %} Botón de login o perfil de usuario {% endcomment %}
    <div class="flex items-center">
      {% if user.is_authenticated %}

      <a href="{% url "tienda:carro" user.id %}">
      <img class="w-5 h-5 rounded-full" src="/media/images/carroBlanco2.png" alt=" img carro">
      </a>

      <a href="{% url 'tienda:usuario_detalle' user.pk %}">
        <button type="button" class="flex items-center text-sm ml-4 bg-gray-800 text-white font-bold  py-2 px-4 rounded" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
            <img class="w-5 h-5 rounded-full" src="/media/images/usuario.png" alt="User Avatar">
            <span class="ml-2">{{ user.username  }}</span>
        </button>
      </a>
      <a href="{% url 'tienda:logout' %}" class="ml-4 text-sm bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">Logout</a>

      {% else %}
      <button type="button" class="flex items-center text-sm bg-gray-800 text-white rounded-full md:me-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
          <span class="ml-2"></span>
      </button>
      <a href="{% url 'tienda:login' %}" class="ml-4 text-sm bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Login</a>
      {% endif %}
    </div>

   
 
    </div>
    <div class="items-center justify-between hidden w-full md:flex md:w-auto md:order-1" id="navbar-user">
      <ul class="flex flex-col font-medium p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:space-x-8 rtl:space-x-reverse md:flex-row md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700">
        
        <li>
          <a href=" {% url "tienda:home" %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Lista de productos</a>
        </li>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url "tienda:tusPost" user.id %}" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Tus Publicaciones</a>
        </li>
        {% endif %}
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Acerca de nosotros</a>
        </li>
        <li>
          <a href="#" class="block py-2 px-3 text-gray-900 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 dark:text-white md:dark:hover:text-blue-500 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700">Contact</a>
        </li>
        
      </ul>
    </div>
    </div>
  </nav>
  


    {% block content %}{% endblock content %}
    
</body>
</html>

templates/index.html
{% extends "base.html" %}

 {% block content %}



 <div class="flex justify-center align-middle">
    <div class="shadow-md rounded-3xl bg-slate-400 mt-32">
        <div class="flex justify-center text-3xl font-bold mt-2">
        <h1>Bienvenido</h1>
        </div>
        <img src="media\images\logo.png" alt="logo">

        <a href="{% url 'tienda:home' %}" style="text-decoration: none; color: inherit;">
        <div class="flex justify-center">         
            <button type="button" 
                    class="group relative w-full flex justify-center py-4 px-4 border border-transparent font-bold text-sm rounded-md text-indigo-600 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">                   
                    ENTRA AQUI</button>
        </div>
        </a>      
    </div>
 </div>


{% endblock content %}

templates/tienda_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<!-- Botón para crear un nuevo artículo -->
<a href="{% url 'tienda:create' %}"><button type="button" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Crear Nuevo Artículo</button></a>

<!-- Bucle para mostrar los posts -->
{% for post in posts %}
<div class="container mx-auto mt-4">
  
  <div class="max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
    <a href="{% url 'tienda:detail' post.id %}">
      <div class="md:flex">
        
        <!-- Muestra la imagen del post -->
        <div class="md:shrink-0">
          {% if post.img %}
          <img class="h-48 w-full object-cover md:h-full md:w-48" src="{{ post.img.url }}" alt="Imagen de {{ post.title }}">
          {% else %}
          <img class="h-48 w-full object-cover md:h-full md:w-48" src="{% static 'default_image.jpg' %}" alt="Imagen por defecto">
          {% endif %}
        </div>

        <!-- Información del post -->
        <div class="p-8">
          <div class="uppercase tracking-wide text-sm text-indigo-500 font-semibold">{{ post.title }}</div>
          <p class="block mt-1 text-lg leading-tight font-medium text-black hover:underline">{{ post.sub_title }}</p>
          <p class="mt-2 text-slate-500">{{ post.content }}</p>
        </div>

      </div>
    </a>
  </div>

</div>  
{% endfor %}

{% endblock content %}